name: 'UNITARY TESTS'

on:
  push:
    branches:
      - main

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '19.9'
      - name: 'Install Dependencies'
        run: 'npm install'
      - name: 'RUN LINT'
        run: |
          'npm run lint'